extends Node
## AUTOLOADED singleton that runs with the game. Reads established config and communicates to FEAGI


var mapping_config: FEAGI_Genome_Mapping
var endpoint_config: FEAGI_Resource_Endpoint
var godot_device_manager: FEAGI_RunTime_GodotDeviceManager = FEAGI_RunTime_GodotDeviceManager.new()

var _FEAGI_device_manager: FEAGI_RunTime_FEAGIDeviceManager = FEAGI_RunTime_FEAGIDeviceManager.new()

var _FEAGI_sensors: Dictionary = {} ## Key'd by the device name, value is the relevant [FEAGI_IOHandler_Sensory_Base]. Beware of name conflicts!
var _FEAGI_sensors_cache: Array[FEAGI_IOHandler_Sensory_Base] = [] ## NOTE: We cache the results of _FEAGI_sensors.values() since its rather slow
var _automatic_device_generator: FEAGIAutomaticDeviceGenerator
var _tick_engine: FEAGI_RunTime_TickEngine

func _enter_tree() -> void:
	initialize_FEAGI_runtime()


	#_tick_engine = FEAGI_RunTime_TickEngine.new()
	#add_child(_tick_engine)




# General overview of startup
# Read / verify configs, stop if not enabled
# Load in sensor / motor FEAGI Device objects
# Activate FEAGI Device manager, including the Debugger and the FEAGI Network Interface (if enabled)
# Activate Godot Device Manager
# Add all devices that have been requested to be auto-generated





# initialize debugger views
# Wait for game tree to be ready
# confirm network connection to feagi
# Overwrite any feagi indexes on the device listing if mentioned in the URL parameters
# Have virtual FEAGI devices register themselves to the FEAGI runtime
# start tick system

func initialize_FEAGI_runtime() -> void:
	print("FEAGI Interface starting up!")
	
	# Read / verify configs, stop if not enabled
	mapping_config = load(FEAGI_PLUGIN.get_genome_mapping_path())
	endpoint_config = load(FEAGI_PLUGIN.get_endpoint_path())
	if !mapping_config:
		push_error("FEAGI: No settings found for FEAGI configuration! The FEAGI integration will now halt!")
		return
	if !mapping_config.FEAGI_enabled:
		push_warning("FEAGI: FEAGI disabled as per configuration")
		return
	if !endpoint_config:
		push_error("FEAGI: No connection settings found for FEAGI configuration! THe FEAGI integration will now halt!")
		return
	
	# Load in sensor / motor FEAGI Device objects
	for incoming_FEAGI_sensor in mapping_config.sensors.values():
		if incoming_FEAGI_sensor is not FEAGI_IOHandler_Sensory_Base:
			push_error("FEAGI: Unknown object attempted to be added as a FEAGI Sensor! Skipping!")
			continue
			
		if (incoming_FEAGI_sensor as FEAGI_IOHandler_Sensory_Base).is_disabled:
			print("FEAGI: Sensor %s is disabled! Not using it for the debugger AND to FEAGI!" % (incoming_FEAGI_sensor as FEAGI_IOHandler_Sensory_Base).device_name)
			continue
		if (incoming_FEAGI_sensor as FEAGI_IOHandler_Sensory_Base).device_name in _FEAGI_sensors:
			push_error("FEAGI: sensor %s is already defined! Ensure there are no motor / sensor devices with repeating names!" % (incoming_FEAGI_sensor as FEAGI_IOHandler_Sensory_Base).device_name)
			continue
		_FEAGI_sensors[(incoming_FEAGI_sensor as FEAGI_IOHandler_Sensory_Base).device_name] = incoming_FEAGI_sensor
	_FEAGI_sensors_cache.assign(_FEAGI_sensors.values())
	
	
	# Activate FEAGI Device manager, including the Debugger and the FEAGI Network Interface (if enabled)
	_FEAGI_device_manager.setup(_FEAGI_sensors, mapping_config.debugger_enabled, mapping_config.FEAGI_enabled)
	
	# Activate Godot Device Manager
	godot_device_manager.setup(_FEAGI_sensors)
	
	# Add all devices that have been requested to be auto-generated
	_automatic_device_generator = FEAGIAutomaticDeviceGenerator.new()
	add_child(_automatic_device_generator)
	_automatic_device_generator.add_all_autogenerated_objects(_FEAGI_sensors_cache)
	
	
	
	
	



	


## Get data from sensors, send to FEAGI, retrieve motor data from FEAGI, send to godot motor devices, update debug information with both
func _FEAGI_tick() -> void:
	# Get sensor data
	
	# Send Sensor data
	
	# Retrieve Motor data
	
	# Apply Motor data
	
	# update debug information

	
	
	
	pass
	
	
	
