extends Node
class_name FEAGIAutomaticDeviceGenerator
## Some devices are not directly added by the user to their scenes, they are set to be created by the plugin directly. This node facilitates that

const DEVICE_SCREENSHOTTER: PackedScene = preload("res://addons/FeagiIntegration/RunTime/VirtualDevices/Sensors/FEAGI_Device_Camera_ScreenCapture.tscn")

## Goes through device arrays, sees if any are calling for an automatically generated Godot Devices, and if so, create them
func add_all_autogenerated_objects(FEAGI_sensors: Dictionary) -> void: # TODO add motors
	for sensor_name in FEAGI_sensors:
		
		if FEAGI_sensors[sensor_name] is FEAGI_IOHandler_Sensory_Camera:
			if (FEAGI_sensors[sensor_name] as FEAGI_IOHandler_Sensory_Camera).automatically_create_screengrabber:
				var screenshoter: FEAGI_Device_Camera_ScreenCapture = DEVICE_SCREENSHOTTER.instantiate()
				add_child(screenshoter)
				screenshoter.setup_screenshot_system((FEAGI_sensors[sensor_name] as FEAGI_IOHandler_Sensory_Camera).device_name)
				screenshoter.register_device()
				continue
				
